### ISSUE TITLE
Icons are listed vertically

### ISSUE THREAD

**Issue by ckdragons** [Malekal4699/fvtt-module-permission-viewer#15]
Sorry to be a bother. It would seem the last update caused the icons to show vertically instead of horizontally as it did with the previous version. Here is a pic showing what I mean.
![image](https://user-images.githubusercontent.com/84493092/126876363-cb8a4bd2-e00d-4006-8942-400682023094.png)
I have tested this by removing all modules from Foundry except Permission Viewer to verify this isn't conflicting with another module. Is this possible to correct, or would you have to revert the update you made to support smol-foundry module?
Thanks.

**Comment by Malekal4699** [comment]
Hi, I should be able to correct that. Likely missing the 5th element... ;)

**Comment by Malekal4699** [comment]
Hi, sorry this took a while, I did not notice it had been 20 days since last check... 👎 
I fixed this so they now are spread horizontal, but there's still a minor issue where they are not aligned to the center of the icons.

**Comment by Malekal4699** [comment]
Fixed with rollback.

**Comment by ghost** [comment]
This doesn't seem to be resolved. Mine are still shown vertically. I tried disabling every other mod in case there was a conflict causing it, but no luck, I tried reinstalling Permission Viewer and that didn't work either. (side note, it initially installs 0.8.8, but then if it ever updates, it will update to 0.8.10. Probably the same thing, but it's a weird little inconsistency)
![Untitled](https://user-images.githubusercontent.com/83744909/138203041-7cfebbfa-1ec8-4474-9365-761160451090.png)
